capturaHost: https://upload.wikimedia.org
capturaPath: wikipedia/commons/d/d9/Test.png

logging:
  level: DEBUG
  loggers:
    "mylogger":
      level: DEBUG
      additive: false
      appenders:
        - type: file
          currentLogFilename: ./log/mylogger.log
          archivedLogFilenamePattern: ./log/mylogger-%d.log.gz
          archivedFileCount: 5
  appenders:
    # Log warnings and errors to stderr
    - type: console
      threshold: DEBUG
      target: stderr